# Generated by Django 6.0.2 on 2026-02-25 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(default='Computer Science & Engineering', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default='Khoka Moni', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='title',
            field=models.CharField(default='Security Researcher · MEC CSE', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='university',
            field=models.CharField(default='Mymensingh Engineering College · University of Dhaka', max_length=200),
        ),
    ]
