# Generated by Django 6.0.2 on 2026-02-25 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_profile_department_alter_profile_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicDegree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_type', models.CharField(choices=[('phd', 'PhD'), ('masters', 'Masters'), ('bachelors', 'Bachelors'), ('hsc', 'Higher Secondary'), ('ssc', 'Secondary')], max_length=20)),
                ('degree_name', models.CharField(max_length=200)),
                ('field_of_study', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('grade_value', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('grade_scale', models.DecimalField(decimal_places=2, default=4.0, max_digits=4)),
                ('grade_display', models.CharField(blank=True, help_text="e.g., '5.00 / 5.00'", max_length=50)),
                ('class_rank', models.IntegerField(blank=True, null=True)),
                ('class_size', models.IntegerField(blank=True, null=True)),
                ('rank_percentile', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('description', models.TextField(blank=True)),
                ('achievements', models.TextField(blank=True, help_text='Notable achievements during this degree')),
                ('transcript_file', models.FileField(blank=True, null=True, upload_to='transcripts/')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-start_date', 'order'],
            },
        ),
        migrations.CreateModel(
            name='AcademicHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('icon_class', models.CharField(default='fa-solid fa-star', max_length=50)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AcademicInstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(blank=True, max_length=50)),
                ('institution_type', models.CharField(choices=[('university', 'University'), ('college', 'College'), ('school', 'School')], max_length=20)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='institutions/')),
                ('website', models.URLField(blank=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AcademicHonor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('honor_type', models.CharField(choices=[('award', 'Award'), ('scholarship', 'Scholarship'), ('honor', 'Honor'), ('prize', 'Prize')], max_length=20)),
                ('date_received', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('icon_class', models.CharField(default='fa-solid fa-medal', max_length=50)),
                ('color_gradient', models.CharField(default='linear-gradient(145deg, #ffd700, #ffed4e)', max_length=100)),
                ('text_color', models.CharField(default='#8B4513', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('degree', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='honors', to='portfolio.academicdegree')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.academicinstitution')),
            ],
            options={
                'ordering': ['-date_received', 'order'],
            },
        ),
        migrations.AddField(
            model_name='academicdegree',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='degrees', to='portfolio.academicinstitution'),
        ),
        migrations.CreateModel(
            name='AcademicTimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('conference', 'Conference'), ('workshop', 'Workshop'), ('training', 'Training'), ('exchange', 'Exchange Program'), ('other', 'Other')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('order', models.IntegerField(default=0)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.academicinstitution')),
            ],
            options={
                'ordering': ['-start_date', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(blank=True, max_length=20)),
                ('course_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('grade', models.CharField(blank=True, max_length=10)),
                ('is_core', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='portfolio.academicdegree')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
