# Generated by Django 6.0.2 on 2026-02-26 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_project_projectcollaborator_projectimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=200)),
                ('department', models.CharField(blank=True, max_length=200)),
                ('affiliation_type', models.CharField(choices=[('academic', 'Academic Position'), ('industrial', 'Industrial Training'), ('professional', 'Professional Membership'), ('visiting', 'Visiting Position'), ('other', 'Other')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('display_date', models.CharField(blank=True, help_text="Custom date display like 'August 2024 - June 2025'", max_length=100)),
                ('description', models.TextField(blank=True)),
                ('responsibilities', models.TextField(blank=True, help_text='Key responsibilities')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='affiliations/')),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('website_url', models.URLField(blank=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-start_date', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ProfessionalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=200)),
                ('service_type', models.CharField(choices=[('reviewer', 'Journal Reviewer'), ('committee', 'Committee Member'), ('board', 'Advisory Board'), ('organizer', 'Conference Organizer'), ('member', 'Professional Member')], max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-start_date', 'order'],
            },
        ),
        migrations.CreateModel(
            name='TaughtCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=20)),
                ('course_name', models.CharField(max_length=200)),
                ('level', models.CharField(blank=True, help_text='e.g., Undergraduate, Graduate', max_length=50)),
                ('semester', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('affiliation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses_taught', to='portfolio.affiliation')),
            ],
            options={
                'verbose_name': 'Taught Course',
                'verbose_name_plural': 'Taught Courses',
                'ordering': ['order'],
            },
        ),
    ]
