# Generated by Django 6.0.2 on 2026-02-26 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_affiliation_professionalservice_taughtcourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='MOOCCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'MOOC Category',
                'verbose_name_plural': 'MOOC Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MOOCProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='mooc/logos/')),
                ('website', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'MOOC Provider',
                'verbose_name_plural': 'MOOC Providers',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MOOCCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('instructor', models.CharField(blank=True, help_text='Course instructor(s)', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('skills', models.CharField(blank=True, help_text='Comma-separated skills learned', max_length=500)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', max_length=20)),
                ('completion_date', models.DateField()),
                ('completion_percentage', models.IntegerField(default=100, help_text='Percentage completed')),
                ('credential_id', models.CharField(blank=True, help_text='Certificate ID', max_length=100)),
                ('credential_url', models.URLField(blank=True, help_text='Link to verify credential')),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='mooc/certificates/')),
                ('course_image', models.ImageField(blank=True, null=True, upload_to='mooc/images/')),
                ('duration_hours', models.IntegerField(default=0, help_text='Estimated duration in hours')),
                ('featured', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='portfolio.moocprovider')),
            ],
            options={
                'verbose_name': 'MOOC Course',
                'verbose_name_plural': 'MOOC Courses',
                'ordering': ['-completion_date', 'order'],
            },
        ),
        migrations.CreateModel(
            name='MOOCCourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_courses', to='portfolio.mooccategory')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_categories', to='portfolio.mooccourse')),
            ],
            options={
                'unique_together': {('course', 'category')},
            },
        ),
    ]
