# Generated by Django 6.0.2 on 2026-02-26 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_mooccategory_moocprovider_mooccourse_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#6dbfda', help_text='Hex color code for category', max_length=20)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Blog Category',
                'verbose_name_plural': 'Blog Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('post_type', models.CharField(choices=[('article', 'Research Article'), ('tutorial', 'Tutorial'), ('note', 'Technical Note'), ('review', 'Literature Review'), ('opinion', 'Opinion Piece'), ('update', 'Project Update')], default='article', max_length=20)),
                ('coauthors', models.CharField(blank=True, help_text='Comma-separated list of co-authors', max_length=500)),
                ('excerpt', models.TextField(blank=True, help_text='Short summary for preview', max_length=500)),
                ('content', models.TextField()),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog/images/')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='blog/banners/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('private', 'Private')], default='draft', max_length=20)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('doi', models.CharField(blank=True, help_text='DOI if applicable', max_length=100)),
                ('arxiv_id', models.CharField(blank=True, help_text='arXiv ID if applicable', max_length=100)),
                ('citations', models.IntegerField(default=0, help_text='Number of citations')),
                ('reading_time_minutes', models.IntegerField(default=5)),
                ('views', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('meta_description', models.CharField(blank=True, max_length=200)),
                ('keywords', models.CharField(blank=True, help_text='Comma-separated keywords', max_length=500)),
                ('featured', models.BooleanField(default=False)),
                ('pinned', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(blank=True, related_name='posts', to='portfolio.blogcategory')),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='portfolio.blogtag')),
            ],
            options={
                'ordering': ['-pinned', '-published_date', '-created_date'],
            },
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True)),
                ('content', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
                ('is_spam', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='portfolio.blogcomment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='portfolio.blogpost')),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
        migrations.CreateModel(
            name='BlogReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citation_key', models.CharField(help_text='Unique key for citation', max_length=100)),
                ('reference_type', models.CharField(choices=[('article', 'Journal Article'), ('book', 'Book'), ('conference', 'Conference Paper'), ('thesis', 'Thesis'), ('web', 'Website'), ('other', 'Other')], default='article', max_length=20)),
                ('authors', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('year', models.IntegerField()),
                ('journal', models.CharField(blank=True, max_length=300)),
                ('volume', models.CharField(blank=True, max_length=50)),
                ('issue', models.CharField(blank=True, max_length=50)),
                ('pages', models.CharField(blank=True, max_length=50)),
                ('publisher', models.CharField(blank=True, max_length=200)),
                ('doi', models.CharField(blank=True, max_length=100)),
                ('url', models.URLField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='portfolio.blogpost')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BlogSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='blog/series/')),
                ('order', models.IntegerField(default=0)),
                ('posts', models.ManyToManyField(blank=True, related_name='series', to='portfolio.blogpost')),
            ],
            options={
                'verbose_name': 'Blog Series',
                'verbose_name_plural': 'Blog Series',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['-published_date'], name='portfolio_b_publish_160b5e_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['status', 'published_date'], name='portfolio_b_status_a3fa2f_idx'),
        ),
    ]
