# Generated by Django 6.0.2 on 2026-02-27 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_contactmessage_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicdegree',
            name='degree_type',
            field=models.CharField(choices=[('phd', 'PhD'), ('masters', 'Masters'), ('bachelors', 'Bachelors'), ('hsc', 'Higher Secondary'), ('ssc', 'Secondary'), ('jsc', 'Junior'), ('psc', 'Primary')], max_length=20),
        ),
        migrations.AlterField(
            model_name='academicinstitution',
            name='institution_type',
            field=models.CharField(choices=[('university', 'University'), ('college', 'College'), ('High school', 'High School'), ('Kindergarten', 'Kindergarten')], max_length=20),
        ),
        migrations.CreateModel(
            name='CVE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_id', models.CharField(help_text='e.g., CVE-2024-12345', max_length=20, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('none', 'None')], default='medium', max_length=20)),
                ('cvss_score', models.DecimalField(blank=True, decimal_places=1, help_text='CVSS v3 score', max_digits=3, null=True)),
                ('cvss_vector', models.CharField(blank=True, help_text='CVSS vector string', max_length=100)),
                ('published_date', models.DateField()),
                ('reserved_date', models.DateField(blank=True, null=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('published', 'Published'), ('reserved', 'Reserved'), ('rejected', 'Rejected'), ('disputed', 'Disputed')], default='published', max_length=20)),
                ('affected_products', models.TextField(help_text='Comma-separated list of affected products/versions')),
                ('vulnerability_type', models.CharField(blank=True, help_text='e.g., Buffer Overflow, XSS, SQLi', max_length=100)),
                ('nvd_url', models.URLField(blank=True, help_text='NVD link')),
                ('mitre_url', models.URLField(blank=True, help_text='MITRE link')),
                ('github_advisory_url', models.URLField(blank=True)),
                ('has_poc', models.BooleanField(default=False)),
                ('poc_url', models.URLField(blank=True, help_text='Link to PoC code')),
                ('poc_file', models.FileField(blank=True, null=True, upload_to='cve/poc/')),
                ('credit_line', models.CharField(blank=True, help_text='How credit was given', max_length=500)),
                ('references', models.TextField(blank=True, help_text='Additional references, one per line')),
                ('featured', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('discovery_date', models.DateField(blank=True, null=True)),
                ('disclosure_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'CVE',
                'verbose_name_plural': 'CVEs',
                'ordering': ['-published_date', '-discovery_date', 'order'],
                'indexes': [models.Index(fields=['-published_date'], name='portfolio_c_publish_4fd161_idx'), models.Index(fields=['severity'], name='portfolio_c_severit_830fd5_idx'), models.Index(fields=['cve_id'], name='portfolio_c_cve_id_180b8a_idx')],
            },
        ),
        migrations.CreateModel(
            name='CVEAcknowledgment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('cve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgments', to='portfolio.cve')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CVEAffectedVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=200)),
                ('version', models.CharField(max_length=100)),
                ('version_type', models.CharField(blank=True, help_text="e.g., '=' , '<=', '>='", max_length=50)),
                ('cve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='portfolio.cve')),
            ],
            options={
                'ordering': ['product', 'version'],
            },
        ),
    ]
