# Generated by Django 6.0.2 on 2026-02-27 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_alter_academicdegree_degree_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
