# Generated by Django 6.0.2 on 2026-02-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_profile_bio_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='school',
            field=models.CharField(default='Mymensingh Engineering College', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='university',
            field=models.CharField(default='University of Dhaka', max_length=200),
        ),
    ]
