# Generated by Django 6.0.2 on 2026-02-28 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_profile_school_alter_profile_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='orcid_id',
            field=models.URLField(blank=True),
        ),
    ]
