# Generated by Django 6.0.2 on 2026-02-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_alter_profile_orcid_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='alias',
            field=models.CharField(blank=True, help_text='Nickname or alias', max_length=100),
        ),
    ]
